# Generated by Django 4.2.6 on 2023-10-26 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("type", models.CharField(blank=True, max_length=30, null=True)),
                ("store", models.CharField(blank=True, max_length=55, null=True)),
                ("language", models.CharField(blank=True, max_length=20, null=True)),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                ("final_link", models.CharField(blank=True, max_length=255, null=True)),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="page_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "media_buyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="page_media_buyer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.product",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="LandingPage",
        ),
    ]
