# Generated by Django 4.2.6 on 2023-11-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_user_managers_remove_user_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="upsell_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
