# Generated by Django 4.2.6 on 2023-11-19 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_product_upsell_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creative",
            name="script",
        ),
        migrations.RemoveField(
            model_name="creative",
            name="voice_over_link",
        ),
        migrations.CreateModel(
            name="VoiceOver",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("language", models.CharField(blank=True, max_length=20, null=True)),
                ("script", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                ("final_link", models.CharField(blank=True, max_length=255, null=True)),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "media_buyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="voice_over_media_buyer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.product",
                    ),
                ),
                (
                    "voice_over",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="voice_over_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
