# Generated by Django 4.2.6 on 2023-11-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_creative_script_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creative",
            name="status",
            field=models.CharField(
                blank=True, default="To Do", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="status",
            field=models.CharField(
                blank=True, default="To Do", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Client", "Client"),
                    ("Media Buyer", "Media Buyer"),
                    ("Page Builder", "Page Builder"),
                    ("Voice Over", "Voice Over"),
                    ("Video Editor", "Video Editor"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="voiceover",
            name="status",
            field=models.CharField(
                blank=True, default="To Do", max_length=20, null=True
            ),
        ),
    ]
