# Generated by Django 4.2.6 on 2023-11-27 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_user_managers_remove_campaign_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="user",
            new_name="client",
        ),
    ]
