# Generated by Django 4.2.6 on 2023-11-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_rename_user_product_client"),
    ]

    operations = [
        migrations.RenameField(
            model_name="campaign",
            old_name="stated_date",
            new_name="started_date",
        ),
    ]
