# Generated by Django 4.2.6 on 2023-11-27 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_rename_stated_date_campaign_started_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="cpp",
        ),
        migrations.AlterField(
            model_name="campaign",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaign_client",
                to="api.client",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_media_buyer",
                to="api.client",
            ),
        ),
    ]
