# Generated by Django 4.2.6 on 2023-11-28 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_remove_campaign_cpp_alter_campaign_client_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "transaction_link",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "payment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Membership", "Membership"),
                            ("Ads Balance", "Ads Balance"),
                            ("Leads Commission", "Leads Commission"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_client",
                        to="api.client",
                    ),
                ),
            ],
        ),
    ]
