# Generated by Django 4.2.6 on 2023-11-28 14:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="approved",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Approved", "Approved"),
                    ("Waiting Approval", "Waiting Approval"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Membership", "Membership"),
                    ("Ads Balance", "Ads Balance"),
                    ("Leads Balance", "Leads Balance"),
                    ("Wrong Orders", "Wrong Orders"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
