# Generated by Django 4.2.6 on 2023-11-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_payment_approved_alter_payment_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="approved",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Approved", "Approved"),
                    ("Waiting Approval", "Waiting Approval"),
                ],
                default="Waiting Approval",
                max_length=20,
                null=True,
            ),
        ),
    ]
