# Generated by Django 4.2.6 on 2023-12-04 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_campaign_amount_spent_alter_campaign_budget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaign_client",
                to="api.client",
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="media_buyer",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "Media Buyer"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaign_media_buyer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.product",
            ),
        ),
        migrations.AlterField(
            model_name="creative",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "Video Editor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="creative_creator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="creative",
            name="format",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Reel (9:16)", "Reel (9:16)"),
                    ("Square (1:1)", "Square (1:1)"),
                    ("widescreen (16:19)", "widescreen (16:19)"),
                    ("Vertical (4:5)", "Vertical (4:5)"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="creative",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Arabic", "Arabic"),
                    ("French", "French"),
                    ("English", "English"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="creative",
            name="media_buyer",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "Media Buyer"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="creative_media_buyer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="creative",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.product",
            ),
        ),
        migrations.AlterField(
            model_name="creative",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("To Do", "To Do"),
                    ("In Progress", "In Progress"),
                    ("Done", "Done"),
                ],
                default="To Do",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="creative",
            name="voice_over",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="creative_voice_over",
                to="api.voiceover",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "Page Creator"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="page_creator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Arabic", "Arabic"),
                    ("French", "French"),
                    ("English", "English"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="media_buyer",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "Media Buyer"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="page_media_buyer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.product",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("To Do", "To Do"),
                    ("In Progress", "In Progress"),
                    ("Done", "Done"),
                ],
                default="To Do",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Product Page", "Product Page"),
                    ("Landing Page", "Landing Page"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_media_buyer",
                to="api.client",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Manager", "Manager"),
                    ("Client", "Client"),
                    ("Media Buyer", "Media Buyer"),
                    ("Page Builder", "Page Builder"),
                    ("Voice Over", "Voice Over"),
                    ("Video Editor", "Video Editor"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="voiceover",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "Voice Over"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="voice_over_creator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="voiceover",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Arabic", "Arabic"),
                    ("French", "French"),
                    ("English", "English"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="voiceover",
            name="media_buyer",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "Media Buyer"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="voice_over_media_buyer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="voiceover",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.product",
            ),
        ),
        migrations.AlterField(
            model_name="voiceover",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("To Do", "To Do"),
                    ("In Progress", "In Progress"),
                    ("Done", "Done"),
                ],
                default="To Do",
                max_length=20,
                null=True,
            ),
        ),
    ]
