# Generated by Django 4.2.6 on 2023-12-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_alter_campaign_client_alter_campaign_media_buyer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="commission",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="membership",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
