# Generated by Django 4.2.6 on 2023-12-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_client_commission_client_membership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="approved",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Approved", "Approved"),
                    ("Waiting Approval", "Waiting Approval"),
                    ("Not Approved", "Not Approved"),
                ],
                default="Waiting Approval",
                max_length=20,
                null=True,
            ),
        ),
    ]
