# Generated by Django 4.2.6 on 2023-12-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_alter_payment_approved"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="approved",
            new_name="status",
        ),
    ]
