# Generated by Django 4.2.6 on 2023-12-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_rename_approved_payment_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="payment_type",
            new_name="type",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="transaction_link",
        ),
        migrations.AddField(
            model_name="payment",
            name="proof",
            field=models.FileField(blank=True, null=True, upload_to="payment_proofs/"),
        ),
    ]
