# Generated by Django 4.2.6 on 2023-12-05 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_alter_client_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="membership",
        ),
    ]
