# Generated by Django 4.2.6 on 2023-12-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_remove_client_membership"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile",
            field=models.FileField(blank=True, null=True, upload_to="user_profiles/"),
        ),
    ]
