# Generated by Django 4.2.6 on 2023-12-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Testing", "Testing"),
                    ("Scaling", "Scaling"),
                    ("Affiliate", "Affiliate"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
