# Generated by Django 4.2.6 on 2023-12-09 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_alter_product_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "Page Builder"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="page_creator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
