# Generated by Django 4.2.6 on 2023-12-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_remove_client_media_buyer_product_media_buyer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="products/"),
        ),
    ]
