# Generated by Django 4.2.6 on 2023-12-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.FileField(
                blank=True,
                default="products/product_default.png",
                null=True,
                upload_to="products/",
            ),
        ),
    ]
